# Analysis of Traffic Collision Patterns: Time, Weather and Road Factors

### Step 1: TorontoCollisions Data Loading from CSV to python dataframe:

In [25]:
#import required libraries
import pandas as pd
import csv

import mysql.connector
from mysql.connector import errorcode
#!pip install tabulate
#from tabulate import tabulate

import matplotlib.pyplot as plt

#!pip install SQLAlchemy pymysql
from sqlalchemy import create_engine

import re

In [31]:
# TorontoCollisions
url_TorontoCollisions = "https://raw.githubusercontent.com/anithamonica/DATA604_TrafficIncidents/main/datasets/TorontoCollisionsSummary.csv"
dfToronto = pd.read_csv(url_TorontoCollisions)
display(dfToronto.head())

,Year,Month,DayofWeek,HourRange,CountofCollisions,NoofFatalities,CountofInjuryCollsn,CountOfPedestrianCollsn,CountofFatalityCollsn
0,2014,April,Friday,Early Afternoon,133,0,11,5,0
1,2014,April,Friday,Early Morning,9,0,4,1,0
2,2014,April,Friday,Evening,77,0,10,1,0
3,2014,April,Friday,Late Afternoon,176,0,21,4,0
4,2014,April,Friday,Late Night,11,0,3,0,0

In [33]:
#display shape, columns, and data types
print("----------------------------------------------------------------------------")
print("\033[1m"+"Data Analysis of TorontoCollisions"+"\033[0m")
print("----------------------------------------------------------------------------")
print("1.\tShape of the TorontoCollisions dataset:", dfToronto.shape)
print("2.\tNumber of records or rows of the DataFrame:", dfToronto.shape[0])
print("3.\tColumns and Data types of each column:\n", dfToronto.dtypes)
dfTorontoLength = len(dfToronto)

----------------------------------------------------------------------------
Data Analysis of TorontoCollisions
----------------------------------------------------------------------------
1.	Shape of the TorontoCollisions dataset: (5375, 9)
2.	Number of records or rows of the DataFrame: 5375
3.	Columns and Data types of each column:
 Year                        int64
Month                      object
DayofWeek                  object
HourRange                  object
CountofCollisions           int64
NoofFatalities              int64
CountofInjuryCollsn         int64
CountOfPedestrianCollsn     int64
CountofFatalityCollsn       int64
dtype: object

In [37]:
#Inspecting data for TorontoCollisions Dataframe
missingDataSum = dfToronto.isna().sum()
missingDataPercentage = (dfToronto.isnull().mean() * 100).round(2)
missingData = pd.DataFrame({
    "Missing Count": missingDataSum,
    "Missing Percentage": missingDataPercentage
})

pd.options.display.float_format = '{:.2f}'.format
print("\n\033[1m"+"Missing Count per column:"+"\033[0m")
#print(tabulate(missingData, headers='keys', tablefmt='fancy_grid'))
display(missingData)

print("Unique values")
print("----------------------------------------------------------------------------")
print(dfToronto['Month'].unique())
print(dfToronto['Year'].unique())
print(dfToronto['RoadAlignment'].unique())
print(dfToronto['Weather'].unique())

Missing Count per column:

                         Missing Count  Missing Percentage
Year                                 0                0.00
Month                                0                0.00
DayofWeek                            0                0.00
HourRange                            0                0.00
CountofCollisions                    0                0.00
NoofFatalities                       0                0.00
CountofInjuryCollsn                  0                0.00
CountOfPedestrianCollsn              0                0.00
CountofFatalityCollsn                0                0.00

Unique values
----------------------------------------------------------------------------
['April' 'August' 'December' 'February' 'January' 'July' 'June' 'March'
 'May' 'November' 'October' 'September']
[2014 2015 2016 2017 2018 2019 2020 2021]

### Step 3: Data preprocessing

In [39]:
#Introduce new Column : Season
#----------------------------------------------------------------------------
# Mapping from month name to season
monthToSeason = {
    'December': 'Winter', 'January': 'Winter', 'February': 'Winter',
    'March': 'Spring', 'April': 'Spring', 'May': 'Spring',
    'June': 'Summer', 'July': 'Summer', 'August': 'Summer',
    'September': 'Fall', 'October': 'Fall', 'November': 'Fall'
}
dfToronto['Season'] = dfToronto['Month'].map(monthToSeason)
print("Column 'Season' is inserted")
display(dfToronto.head(5))

Column 'Season' is inserted

,Year,Month,DayofWeek,HourRange,CountofCollisions,NoofFatalities,CountofInjuryCollsn,CountOfPedestrianCollsn,CountofFatalityCollsn,Season
0,2014,April,Friday,Early Afternoon,133,0,11,5,0,Spring
1,2014,April,Friday,Early Morning,9,0,4,1,0,Spring
2,2014,April,Friday,Evening,77,0,10,1,0,Spring
3,2014,April,Friday,Late Afternoon,176,0,21,4,0,Spring
4,2014,April,Friday,Late Night,11,0,3,0,0,Spring

### Step 3: Import cleaned TorontoCollisions dataset to MySQL database

In [ ]:
USER = "student"
DB   = "student"
    
# attempt a connection
myconnection = mysql.connector.connect(user=USER, 
                                       password='Bi3KSjqgrNOOL',
                                       host='127.0.0.1', 
                                       port=3306,
                                       database=DB,
                                       allow_local_infile=True)
myconnection

In [ ]:
# Create table TorontoCollisions
queryCreate = '''CREATE TABLE student.TorontoCollisions(
    Year int, 
    Month varchar(15),
    DayofWeek varchar(15),
    TimeSegment varchar(20),
    CountofCollisions int,
    NoofFatalities int,
    CountofInjuryCollsn int,
    CountOfPedestrianCollsn int,
    CountofFatalityCollsn int,
    Season varchar(10));'''

createCursor = myconnection.cursor()
try:
    createCursor.execute(queryCreate)
    print("TorontoCollisions table created successfully!")
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_TABLE_EXISTS_ERROR:
        print("Error! Table TorontoCollisions is already created.")
    else:
        print(err.msg)

createCursor.close()

In [ ]:
# Insert into table TorontoCollisions
insertCursor = myconnection.cursor()

try:
    myconnection.start_transaction()

    for i, currentRow in dfToronto.iterrows():
        insertCommand = "INSERT INTO `TorontoCollisions` VALUES (" + "%s," * (len(currentRow) - 1) + "%s)"
        insertCursor.execute(insertCommand, tuple(currentRow))

    myconnection.commit()
    print("TorontoCollisions: Inserted records successfully")

except Exception as e:
    myconnection.rollback()
    print("Transaction rolled back due to error:", e)

finally:
    insertCursor.close()

In [ ]:
read_cursor = myconnection.cursor(buffered=True, dictionary=True)
query_string = ("SELECT COUNT(*) FROM TorontoCollisions;")
read_cursor.execute(query_string)

for (library_value) in read_cursor:
    print(library_value)
read_cursor.close()
myconnection.close()

### Step 4: TorontoCollisions data analysis and visualization

 - Do Toronto’s peak hours/months/day of weeks differ from overall patterns?
 - Compare weather-impacted months (do Toronto’s weather collisions align with national averages?)
 - Are Toronto’s urban road class collisions match national distributions?

In [ ]:
USER = "student"
DB   = "student"
PWD = "Bi3KSjqgrNOOL"

engine = create_engine(
    f"mysql+mysqlconnector://{USER}:{PWD}@127.0.0.1:3306/{DB}"
)


# Do Toronto’s peak hours/months/day of weeks differ from overall patterns?
queryMonthly = '''SELECT TimeSegment, Month, DayofWeek, 
       MAX(CountofCollisions) AS PeakCollisions
FROM student.TorontoCollisions
GROUP BY TimeSegment, Month, DayofWeek
ORDER BY PeakCollisions DESC;'''
result = pd.read_sql_query(queryMonthly, engine)
display(result)


# Pivot so each SpeedLimit shows Urban and Rural side-by-side
pivot_df = result.pivot(index='SpeedValue', columns='RoadClass', values='InjurySeverity')

# Plot
pivot_df.plot(kind='bar', figsize=(14, 6))
plt.title('Injury Severity by Speed Limit and Road Class')
plt.ylabel('Injury Severity')
plt.xticks(rotation=45)
plt.ylim(bottom=1.0) 
plt.legend(title='Road Class', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()
'''

In [ ]:
#Do collisions spike during certain months, days of the week, or times of day?
queryMonthly = '''SELECT Month, SUM(CountofCollisions) AS TotalCollisions 
FROM TorontoCollisions
GROUP BY Month
ORDER BY TotalCollisions DESC;'''
monthlyCollisions = pd.read_sql_query(queryMonthly, engine)
display(monthlyCollisions)


queryDayOfWeek = '''SELECT DayOfWeek, SUM(CountofCollisions) AS TotalCollisions 
FROM TorontoCollisions
GROUP BY DayOfWeek
ORDER BY TotalCollisions DESC;'''
weeklyCollisions = pd.read_sql_query(queryDayOfWeek, engine)
display(weeklyCollisions)


queryHourly = '''SELECT CollisionHour, TimeSegment, SUM(CountofCollisions) AS TotalCollisions 
FROM TorontoCollisions
GROUP BY CollisionHour, TimeSegment
ORDER BY TotalCollisions DESC;'''
hourlyCollisions = pd.read_sql_query(queryHourly, engine)
display(hourlyCollisions)

In [ ]:
#weather-impacted months
#Which season impact collision frequency and severity? 
queryMonthly = '''SELECT Season, SUM(CountofCollisions) AS TotalCollisions,
FROM TorontoCollisions
GROUP BY Season
ORDER BY TotalCollisions DESC;'''
result = pd.read_sql_query(queryMonthly, engine)
display(result)

In [ ]:
engine.dispose()